apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: testdb-creds
  namespace: test
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "test-rds-secret"
        objectType: "secretsmanager"
