apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: proddb-creds
  namespace: production
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "production-rds-secret"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: dbusername
          - path: password
            objectAlias: dbpassword
          - path: host
            objectAlias: dbhost
          - path: dbname
            objectAlias: dbname
      - objectName: "flask-secret-key"
        objectType: "secretsmanager"
        jmesPath:
          - path: key
            objectAlias: flaskkey
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: production-rds-secret
      type: Opaque
      data:
        #- objectName: <objectName> or <objectAlias>
        - objectName: dbusername
          key: dbusername
        - objectName: dbpassword
          key: dbpassword
        - objectName: dbhost
          key: dbhost
        - objectName: dbname
          key: dbname
    - secretName: flask-secret-key
      type: Opaque
      data:
        #- objectName: <objectName> or <objectAlias>
        - objectName: flaskkey
          key: flaskkey
