apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
  namespace: test
spec:
  serviceAccountName: secrets-manager-csi-aws-provider-sa
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c", "--"]
    args: ["while true; do sleep 30; done;"]
    volumeMounts:
      - name: secrets-store-inline
        mountPath: "/mnt/secrets"
        readOnly: true
    env:
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: test-db-secret
            key: dbusername
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: test-db-secret
            key: dbpassword
      - name: DB_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: test-db-secret
            key: dbhostname


    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: testdb-creds
status: {}
