"""Added blog_title_str to blog_posts table.

Revision ID: 05d3bb439d8c
Revises: 7151f8722ea4
Create Date: 2023-03-09 13:35:54.452389

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "05d3bb439d8c"
down_revision = "7151f8722ea4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("blog_title_str", sa.String(length=250), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.drop_column("blog_title_str")

    # ### end Alembic commands ###
