"""Added Post Views and Post Likes to Blog Posts Table

Revision ID: cc68159c4911
Revises: f282bbf9eb17
Create Date: 2023-08-21 10:39:40.696524

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "cc68159c4911"
down_revision = "f282bbf9eb17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("post_views", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("post_likes", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.drop_column("post_likes")
        batch_op.drop_column("post_views")

    # ### end Alembic commands ###
