"""Added is_draft column

Revision ID: f282bbf9eb17
Revises: 05d3bb439d8c
Create Date: 2023-08-17 12:25:10.411320

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f282bbf9eb17"
down_revision = "05d3bb439d8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_draft", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog_posts", schema=None) as batch_op:
        batch_op.drop_column("is_draft")

    # ### end Alembic commands ###
