apiVersion: v1
kind: Pod
metadata:
  name: logging-sidecar
  namespace: baz
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do echo Logging data > /output/output.log; sleep 5; done"]
    volumeMounts:
    - mountPath: /output
      name: sidecar-vol

  - name: sidecar
    image: busybox
    command: ["sh", "-c", "cat /intput/output.log"]
    volumeMounts:
    - mountPath: /intput
      name: sidecar-vol

  volumes:
  - name: sidecar-vol
    emptyDir: {}
sidecar_pod_logging.yaml (END)
