name: Run Python Linters and Tests on PRs
on: [pull_request] # Triggers the workflow onpull request events

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Pre-commit and perform linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Install Python project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run tests with pytest
        env:
          SECRET_KEY: "temp_key"
          TEST_DATABASE_URI: "sqlite:///"
        run: python -m pytest
